repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: detect-private-key
  -   repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v5.10.1'
      hooks:
        -   id: isort
  -   repo: https://github.com/pycqa/flake8
      rev: '5.0.4'  # pick a git hash / tag to point to
      hooks:
        - id: flake8
  -   repo: local
      hooks:
        - id: pytest
          name: pytest
          entry: bash -c 'py.test'
          language: system
          pass_filenames: false
